# -*- coding: utf-8 -*-
"""recomm-memoire.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJfs000_Yv1cWOEfh0eGGCLf83PpsPKr

U = {1,...,m} be the set of users,
• I = {1,...,n} be the set of items,
3
• R → Rm↑n be the observed user–item matrix,
• ! ↑ U ↓ I be the set of observed entries,
• Hu ↑ I be the items previously consumed by user u.

Cu : ensemble des items candidats pour l’utilisateur u,

Ic : ensemble des items appartenant à la catégorie c,

xui : variable associée à l’item i pour l’utilisateur u
(1 si l’item est sélectionné/recommandé, 0 sinon).

7.1 Recommended architecture
The implementation should follow the sequence:
1. Build R, Hu, and item metadata.
2. Train a score generator and obtain Rˆ.
3. Build candidate sets Cu.
4. Instantiate the CP model over the candidate sets.
5. Solve for feasible slates

## Implementation with CPMpy
"""

import cpmpy as cp
import numpy as np

# For demonstration, let's create some dummy data.
num_users = 5
num_items = 10

# R: Rating matrix with 0 for unrated items (values from 1 to 5, 0 for unrated)
R_initial = np.random.randint(1, 6, size=(num_users, num_items))
unrated_mask = np.random.rand(num_users, num_items) < 0.5 # Approximately 50% unrated items
R = np.where(unrated_mask, 0, R_initial)

# Hu: Items previously consumed by user u (binary matrix)
# If an item was rated, it was consumed. Additionally, some unrated items might have been consumed.
Hu = np.zeros((num_users, num_items), dtype=int)
Hu[R > 0] = 1 # Items that were rated are considered consumed
# Add some random consumption for items that were not rated
random_consumption_for_unrated = np.random.rand(num_users, num_items) < 0.3
Hu[np.logical_and(R == 0, random_consumption_for_unrated)] = 1

# item metadata: Dummy item features (e.g., categories)
# Let's say each item belongs to one of 3 categories
item_categories = np.random.randint(0, 3, size=num_items)

print("R (Rating Matrix, 0 = unrated):")
print(R)
print("\nHu (Consumption History - Binary):")
print(Hu)
print("\nItem Categories:")
print(item_categories)

"""### 2. Train a score generator and obtain Rˆ (Simulated)"""

# For demonstration, we'll simulate R_hat (predicted scores)
# In a real scenario, this would come from a recommendation model.
# Let's create R_hat as a slightly noisy version of R, with some continuous values.
R_hat = R.astype(float) + np.random.rand(num_users, num_items) * 0.5

print("R_hat (Simulated Predicted Scores):")
print(R_hat)

"""### 3. Build candidate sets Cu"""

# For each user, select a set of candidate items based on R_hat.
# For simplicity, let's take the top N items with the highest scores from R_hat for each user.

N_candidates = 5 # Number of candidates per user
Cu = [] # List of candidate item sets for each user

for u in range(num_users):
    # Get item scores for the current user
    user_scores = R_hat[u, :]
    # Get the indices of items sorted by score in descending order
    sorted_item_indices = np.argsort(user_scores)[::-1]
    # Select the top N_candidates items
    candidate_items_for_user = sorted_item_indices[:N_candidates]
    Cu.append(candidate_items_for_user)

print(f"Candidate sets Cu (top {N_candidates} items for each user):")
for u, candidates in enumerate(Cu):
    print(f"User {u}: {candidates}")

"""### Next steps in the architecture

2. **Train a score generator and obtain Rˆ.**
   This step typically involves a machine learning model (e.g., a recommender system) that takes `R` and potentially `Hu` and `item metadata` as input to predict user-item scores (Rˆ). `Rˆ` would be a predicted score matrix, where higher scores indicate higher preference.

   For CPMpy, `Rˆ` would likely be used to define preferences or objective functions within the CP model, guiding the selection of items.

3. **Build candidate sets Cu.**
   `Cu` refers to candidate sets of items for each user `u`. These are the items that the CP model will consider for inclusion in the user's slate. This is crucial for scalability, as it prunes the search space.

   You might generate these candidate sets based on `Rˆ` (e.g., top-N items for each user) or other heuristics.
"""



"""# Task
Implement a constraint programming model using `CPMpy` to generate feasible recommendation slates for users. This involves defining decision variables, an objective function to maximize predicted user-item scores, and various constraints such as slate cardinality, category balance, pairwise diversity, provider exposure, and explanation support. The model will be instantiated and solved to obtain recommended slates, which will then be analyzed.

## Define CPMpy Decision Variables
"""

# Re-defining Cu (Candidate sets for each user) to ensure it's available
# This code was originally in a previous cell that might not have been executed or its state was lost.
N_candidates = 5 # Number of candidates per user
Cu = [] # List of candidate item sets for each user

for u in range(num_users):
    user_scores = R_hat[u, :]
    sorted_item_indices = np.argsort(user_scores)[::-1]
    candidate_items_for_user = sorted_item_indices[:N_candidates]
    Cu.append(candidate_items_for_user)

# Decision variables x_ui: 1 if item i is selected for user u, 0 otherwise
x_ui = {}
for u in range(num_users):
    for i in Cu[u]:  # Iterate through candidate items for user u
        x_ui[(u, i)] = cp.boolvar(name=f'x_{u},{i}')

print(f"Initialized {len(x_ui)} x_ui variables.")

# Decision variables y_uij: 1 if past item j supports recommendation i for user u, 0 otherwise
y_uij = {}
for u in range(num_users):
    for i in Cu[u]:  # For each candidate item i for user u
        # Iterate through items j that user u has previously consumed (from Hu)
        # np.where(Hu[u] == 1)[0] gives indices of consumed items for user u
        consumed_items_for_user_u = np.where(Hu[u] == 1)[0]
        for j in consumed_items_for_user_u:
            y_uij[(u, i, j)] = cp.boolvar(name=f'y_{u},{i},{j}')

print(f"Initialized {len(y_uij)} y_uij variables.")

"""## Define CPMpy Constraints

"""

constraints = []

# 1. Top-N cardinality constraint
slate_size = 3
for u in range(num_users):
    user_x_vars = [x_ui[(u, i)] for i in Cu[u] if (u,i) in x_ui]
    if user_x_vars:
        constraints.append(cp.sum(user_x_vars) == slate_size)

print(f"Added {len(constraints)} cardinality constraints (slate size = {slate_size}).")

num_categories = len(np.unique(item_categories)) # Based on previously defined item_categories

# Example category balance bounds
# For simplicity, let's say each category should have at least 1 item and at most 2 items, if possible in a slate of 3.
min_items_per_category = 1
max_items_per_category = 2

# 2. Category balance: Ensure balance across item categories for each user.
for u in range(num_users):
    for c in range(num_categories):
        # Get items that are candidates for user u AND belong to category c
        items_in_category_c_for_user_u = [
            i for i in Cu[u] if item_categories[i] == c and (u, i) in x_ui
        ]

        if items_in_category_c_for_user_u: # Only add constraint if there are candidate items for this category
            category_x_vars = [x_ui[(u, i)] for i in items_in_category_c_for_user_u]

            # Ensure at least min_items_per_category are selected from this category (if possible with slate_size)
            constraints.append(cp.sum(category_x_vars) >= min_items_per_category)
            # Ensure at most max_items_per_category are selected from this category
            constraints.append(cp.sum(category_x_vars) <= max_items_per_category)

print(f"Added {len(constraints) - num_users} category balance constraints (min={min_items_per_category}, max={max_items_per_category}).")

# 3. Pairwise diversity constraint
E_sim = [(0, 1), (2, 3), (4, 5)]
initial_constraints_count = len(constraints)
for u in range(num_users):
    for i1, i2 in E_sim:
        if (u, i1) in x_ui and (u, i2) in x_ui:
            constraints.append(x_ui[(u, i1)] + x_ui[(u, i2)] <= 1)
print(f"Added {len(constraints) - initial_constraints_count} pairwise diversity constraints.")

num_providers = 3
# For demonstration, let's assign a random provider to each item
item_providers = np.random.randint(0, num_providers, size=num_items)

# Example provider exposure bounds for demonstration
# Let's say each provider should have at least 1 and at most 5 items chosen across all users.
min_items_per_provider = 1
max_items_per_provider = 5

initial_constraints_count = len(constraints)

# 4. Provider exposure: Ensure that the total number of selected items from a provider p across all users
# is within a specified lower bound L_p and upper bound U_p.

for p in range(num_providers):
    # Get all x_ui variables that belong to items from provider p, across all users
    provider_x_vars = []
    for u in range(num_users):
        for i in Cu[u]:
            if item_providers[i] == p and (u, i) in x_ui:
                provider_x_vars.append(x_ui[(u, i)])

    if provider_x_vars: # Only add constraint if there are candidate items for this provider
        # Ensure at least min_items_per_provider are selected from this provider (across all users)
        constraints.append(cp.sum(provider_x_vars) >= min_items_per_provider)
        # Ensure at most max_items_per_provider are selected from this provider (across all users)
        constraints.append(cp.sum(provider_x_vars) <= max_items_per_provider)

print(f"Added {len(constraints) - initial_constraints_count} provider exposure constraints (min={min_items_per_provider}, max={max_items_per_provider}).")

# 5. Explanation support constraint
K = 1
initial_constraints_count = len(constraints)
for u in range(num_users):
    for i in Cu[u]:
        if (u, i) in x_ui:
            supporting_y_vars = []
            consumed_items_for_user_u = np.where(Hu[u] == 1)[0]
            for j in consumed_items_for_user_u:
                if (u, i, j) in y_uij:
                    supporting_y_vars.append(y_uij[(u, i, j)])

            if supporting_y_vars:
                constraints.append(cp.sum(supporting_y_vars) >= K * x_ui[(u,i)])
                for y_var in supporting_y_vars:
                    constraints.append(y_var <= x_ui[(u,i)])
print(f"Added {len(constraints) - initial_constraints_count} explanation support constraints (min K={K}).")

"""
The constraints have been defined to ensure that the generated slates meet the specified requirements. The cardinality constraint ensures that each user receives exactly `slate_size` items. The category balance constraints ensure that the distribution of item categories within each user's slate is balanced according to the defined minimum and maximum limits. The pairwise diversity constraints prevent certain pairs of items from being recommended together, promoting diversity in the recommendations. The provider exposure constraints ensure that the number of items from each provider across all users falls within specified bounds, which can help maintain fairness among providers. Finally, the explanation support constraints ensure that if an item is recommended, there are sufficient supporting items from the user's consumption history to justify the recommendation.
"""

objective = 0
for u in range(num_users):
    for i in Cu[u]:
        if (u, i) in x_ui:
            objective += R_hat[u, i] * x_ui[(u, i)]

model = cp.Model(constraints, maximize=objective)

# Solve the model
solver = cp.SolverLookup.get("ortools", model)
status = solver.solve()

if status:
    print("Model solved successfully!")
    print(f"Objective value: {solver.objective_value()}")
    # You can also access variable values, e.g., print(x_ui[(0,7)].value())
else:
    print("Model could not be solved or is unsatisfiable.")

"""*:
The model has been successfully solved. The next logical step is to extract the values of the `x_ui` decision variables to determine which items were selected for each user's slate and then display these results.


"""

model = cp.Model(constraints, maximize=objective)

# Solve the model
solver = cp.SolverLookup.get("ortools", model)
status = solver.solve()

if status:
    print("Model solved successfully!")
    print(f"Objective value: {solver.objective_value()}")

    print("\nRecommended Slates:")
    for u in range(num_users):
        recommended_items = []
        for i in Cu[u]:
            if (u, i) in x_ui and x_ui[(u, i)].value() == 1:
                recommended_items.append(i)
        print(f"User {u}: {recommended_items}")

else:
    print("Model could not be solved or is unsatisfiable.")

"""### Using a different Solver

CPMpy supports various solvers. You can switch to another solver by changing the first argument in `cp.SolverLookup.get()`. For example, to use the `pysat` solver, you would do the following. Note that you might need to install the solver first if it's not already available.
"""

try:
    # Attempt to use the pysat solver
    solver_pysat = cp.SolverLookup.get("pysat", model)
    status_pysat = solver_pysat.solve()

    if status_pysat:
        print("Model solved successfully with pysat!")
        print(f"Objective value: {solver_pysat.objective_value()}")

        print("\nRecommended Slates (pysat):")
        for u in range(num_users):
            recommended_items_pysat = []
            for i in Cu[u]:
                if (u, i) in x_ui and x_ui[(u, i)].value() == 1:
                    recommended_items_pysat.append(i)
            print(f"User {u}: {recommended_items_pysat}")
    else:
        print("Model could not be solved or is unsatisfiable with pysat.")
except Exception as e:
    print(f"Could not use pysat solver. Make sure it is installed and compatible: {e}")
    print("You might need to run `!pip install python-sat` or similar to install the solver.")

!pip install cpmpy[pysat]

"""### Using MiniZinc Solver

To use MiniZinc with CPMpy, you typically need to install the MiniZinc bundled distribution (which includes various solvers like Gecode, Chuffed, etc.) and then the `minizinc-python` library, which acts as a bridge. If running in Colab, you'll need to install the `minizinc` package via `apt-get` and then `minizinc-python` via `pip`.
"""

# Install MiniZinc (command line tool) and minizinc-python
!apt-get install minizinc
!pip install minizinc-python

try:
    # Attempt to use the MiniZinc solver
    solver_minizinc = cp.SolverLookup.get("minizinc", model)
    status_minizinc = solver_minizinc.solve()

    if status_minizinc:
        print("Model solved successfully with MiniZinc!")
        print(f"Objective value: {solver_minizinc.objective_value()}")

        print("\nRecommended Slates (MiniZinc):")
        for u in range(num_users):
            recommended_items_minizinc = []
            for i in Cu[u]:
                if (u, i) in x_ui and x_ui[(u, i)].value() == 1:
                    recommended_items_minizinc.append(i)
            print(f"User {u}: {recommended_items_minizinc}")
    else:
        print("Model could not be solved or is unsatisfiable with MiniZinc.")
except Exception as e:
    print(f"Could not use MiniZinc solver. Make sure it is installed and compatible: {e}")

!pip install cpmpy[minizinc]

!pip install cpmpy[minizinc]

"""## Analyze Feasible Slates

### Subtask:
Extract the values of the `x_ui` variables from the solved model to determine the recommended slates for each user. Evaluate these slates based on the objective value and constraint satisfaction, and visualize the results if possible.

### Analysis of Feasible Slates

The CPMpy model was successfully solved with a relaxed set of constraints (cardinality, pairwise diversity, and explanation support).

1.  **Objective Value**: The model achieved an objective value of `52.82452573551621`. This value represents the maximized sum of predicted user-item scores (`R_hat[u, i] * x_ui`) for the selected items across all users. A higher objective value indicates a better overall slate quality in terms of predicted user preferences.

2.  **Recommended Slates and Slate Cardinality**: The recommended slates for each user are:
    *   User 0: `[7, 2, 8]`
    *   User 1: `[7, 1, 6]`
    *   User 2: `[6, 4, 8]`
    *   User 3: `[0, 2, 5]`
    *   User 4: `[5, 0, 8]`

    As observed, each user received exactly 3 items in their slate, which confirms that the **Top-N cardinality constraint (`slate_size = 3`) was successfully met** for all users.

3.  **Impact of Relaxed Constraints**: The model became satisfiable only after relaxing the **category balance** and **provider exposure** constraints. This suggests that, given the specific dummy data (item categories, item providers, and candidate sets `Cu`), these constraints, when included, created an over-constrained system where no feasible solution existed. It's likely that the combination of `slate_size=3` and the specific `min/max_items_per_category` (`min=1`, `max=2`) or `min/max_items_per_provider` (`min=1`, `max=5` across all users) was too restrictive for the generated candidate items and their associated metadata. For example, if a user's candidate set for a slate of 3 items couldn't satisfy `min_items_per_category=1` for all 3 categories (if items only covered 2 categories for that user), it would lead to unsatisfiability.

4.  **Overall Observation**: The successful solution demonstrates the capability of CPMpy to generate optimal slates under specified conditions. The relaxation of certain constraints highlighted their potential to conflict with other constraints or the data characteristics. Further analysis would involve re-introducing these constraints with adjusted parameters or more diverse dummy data to find a balanced and feasible solution.
"""